Algoritmo "Almento de Salario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

salario,almento: real


Inicio

      escreva ("Digite o valor do almento: ")
      leia(salario)
      
      almento <- salario + salario * 15 / 100
      
      escreval("O funcionario teve um almento em seu salario de",almento,)
      

Fimalgoritmo