Algoritmo "Alugel de Carro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

km, dias, total: real


Inicio

      escreva ("Digite os Km percorridos: ")
      leia(km)
      
      escreva ("Digite os dias: ")
      leia(dias)
      
      total <- dias * 90 + km * 0,20
      
      escreval("O total a ser pago do alugel do carro e R$",total,)
      

      

Fimalgoritmo