Algoritmo "Dobro e Divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

km,hm,dam,dm,cm,mm,metro: real


Inicio

      escreva("Digite um valor: ")
      leia(metro)
      
      km <- metro / 1000
      
      hm <- metro / 100
      
      dam <- metro / 10
      
      dm <- metro / 0,1
      
      cm <- metro * 100
      
      mm <- metro * 1000
      
      escreval("A distância de ",km,"km",hm,"hm",dam,"dam",dm,"dm",cm,"cm",mm,"mm")
      

Fimalgoritmo