Algoritmo "Dias de Vida"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

dia, total: real


Inicio

      escreva ("Digite quantos chigacos fuma por dia: ")
      leia(dia)
      
      total <- dia * 10
      
      escreval("O seu tempo de vida perdido e de:",total," minutos no total. ATENÇÃO PARE DE FUMAR")
      


      

Fimalgoritmo