Algoritmo "Dobro e Divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

dobro, divisao, numero: real


Inicio

      escreva("Digite um valor: ")
      leia(numero)
      
      dobro <- numero * 2
      
      divisao <- numero / 2
      
      escreval(numero, ", O sucessor de ",numero," e " ,dobro," ja o antecessor de ",numero," e ",divisao)

Fimalgoritmo