Algoritmo "Nota de aluno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

nota1,nota2, resultado: real


Inicio

      escreva("Digite um valor: ")
      leia(nota1)

      escreva("Digite um valor: ")
      leia(nota2)

resultado <- (nota1 + nota2)/2

escreval("A entre entre",nota1," e ",nota2," e igual a",resultado)

Fimalgoritmo