Algoritmo "Pintar parede"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

altura, largura, area, tinta:real


Inicio

      escreva("Digite a largura: ")
      leia(largura)
      
      escreva("Digite a altura: ")
      leia(altura)

      area <- altura * largura / 2
      
      escreval("Sera necesario",area," litros de tinta")

Fimalgoritmo