Algoritmo "Preço com Desconto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

preco,desconto: real


Inicio

      escreva ("Digite o valor do produto: ")
      leia(preco)
      
      desconto <- preco - preco * 5 / 100
      
      escreval("O preço promocional com desconto e de",desconto,)
      

Fimalgoritmo