Algoritmo "Real em Dolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

reais,dolares: real


Inicio

      escreva("Digite um valor em reais: ")
      leia(reais)

      dolares <- reais / 5,70

      escreval("Você pode comprar: ",dolares, " Dólares")


Fimalgoritmo