Algoritmo "Salario de funcionario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

salario: real
nome: caracter


Inicio

escreva("Qual e seu nome ?:")
leia(nome)

escreva("Qual seu salario ?:")
leia(salario)

escreval("O ",nome," tem um salário de ",salario," em junho")


Fimalgoritmo