Algoritmo "Salario por Mes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

dias, salario: real


Inicio

      escreva ("Digite os dias trabalhados desse mes: ")
      leia(dias)
      
      salario <- dias * 8 * 25
      
      escreval("O salario do funcionaro sera de R$:",salario)
      


      

Fimalgoritmo