Algoritmo "Seja bem vindo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

nome: caracter


Inicio

      escreva("Qual e seu nome ? :")
      leia(nome)

      escreval("Ola ",nome, " é um prazer te conhecer!")



Fimalgoritmo