Algoritmo "Somatorio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

soma1,soma2, resultado: real


Inicio

      escreva("Digite um valor: ")
      leia(soma1)

      escreva("Digite um valor: ")
      leia(soma2)

resultado <- (soma1 + soma2)

escreval("A soma entre",soma1," e ",soma2," e igual a",resultado)

Fimalgoritmo