Algoritmo "Sucessor e Antecesor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

sucessor, antecessor, numero: real


Inicio

      escreva("Digite um valor: ")
      leia(numero)
      
      sucessor <- numero + 1
      
      antecessor <- numero - 1
      
      escreval(numero, ", O sucessor de ",numero," e " ,sucessor," ja o antecessor de ",numero," e ",antecessor)

Fimalgoritmo