Algoritmo "Valor de delta"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

A, B, C, delta: real


Inicio

      escreva ("Valor de A: ")
      leia(A)
      
      escreva ("Valor de B: ")
      leia(B)
      
      escreva ("Valor de C: ")
      leia(C)
      
      delta <- B * B - 4 * A * C
      
      escreval("O valor de Delta e ",delta,)


Fimalgoritmo