Algoritmo "Medir_Temperatura 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/04/2025

Var celsius, farenheit: real


Inicio

escreva("digite a temperatura em farenheit::   ")
leia(farenheit)

celsius<- (farenheit - 32) * 5/9

escreval ("A tempretura em celsius é de: ", celsius)


Fimalgoritmo