Algoritmo "Medir_Temperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/04/2025

Var celsius, farenheit: real


Inicio

escreva("digite a temperatura em ceusiu:   ")
leia(celsius)

farenheit<- (celsius * 1.8) + 32

escreval ("A tempretura em farenheit é de: ", farenheit)


Fimalgoritmo